# Data

It's all very well being able to access the content, but for the purposes of the kind of things we'd like to do, access to the data is needed. 

Lancaster Newsbook Corpus

## JISC Newspaper digitisation projects
Maybe a separate chapter?

Most of the projects in the UK which have used newspaper data hvae been using the _British Library’s 19th Century Newspapers_ collection. This is an interesting collection of content and worth outlining in some detail. Knowing the sources, geographical makeup and motivation behind the titles in the collection can be really helpful in thinking about what is and is not in the sources. 

The JISC newspaper digitisation program began in 2004, when The British Library received two million pounds from the Joint Information Systems Committee (JISC) to for some digitisation projects. A plan was made to digitise up to two million pages, across 49 titles (reference https://www.gale.com/intl/essays/ed-king-digitisation-of-british-newspapers-1800-1900). A second phase of the project digitised a further 22 titles.[@shaw-newspapers for a good brief overview to the selection process for JISC 1]

>The forty-eight titles chosen represent a very large cross-section of 19th century press and
publishing history. Three principles guided the work of the selection panel: firstly, that
newspapers from all over the UK would be represented in the database; in practice, this
meant selecting a significant regional or city title, from a large number of potential
candidate titles. Secondly, the whole of the nineteenth century would be covered; and
thirdly, that, once a newspaper title was selected, all of the issues available at the British
Library would be digitised. To maximise content, only the last timed edition was
digitised. No variant editions were included. Thirdly, once a newspaper was selected, all
of its run of issue would be digitised.[@ed-king-digi]


Jane Shaw wrote, in 2007: 

>The academic panel made their selection using the following eligibility criteria:

>To ensure that complete runs of newspapers are scanned
>To have the most complete date range, 1800-1900, covered by the titles selected
To have the greatest UK-wide coverage as possible
To include the specialist area of Chartism (many of which are short runs)
To consider the coverage of the title: e.g., the London area; a large urban area (e.g., Birmingham); a larger regional/rural area
To consider the numbers printed - a large circulation
The paper was successful in its time via its sales
To consider the different editions for dailies and weeklies and their importance for article inclusion or exclusion
To consider special content, e.g., the newspaper espoused a certain political viewpoint (radical/conservative)
The paper was influential via its editorials. [@shaw-newspapers]

What's really clear, is that the selection was driven by assumed historical need by the Library's users, plus some practicalities around copyright, microfilm and 

The result was a heavily curated collection, and like all collections created in this way, it is subject to (quite rightly) a lot of scrutiny by historians.

This is all covered in lots of detail elsewhere, including some really interesting critiques of the access and so forth.[@smits_making_2016; @mussell-elemental both include some discussion and critique of the British Library Newspaper Collection] But the overall makeup of it is clear, and this was a very specifically curated collection, though it was also influenced by contingency, in that it used microfilm (sometimes new microfilm). But overall, one might say that the collection has specific historical relevant, and was in ways representative. It does, though, only represent a tiny fraction of the newspaper collection, and by being relevant and restricted to 'important' titles, it does of course miss other voices. For example, much of the Library's collection consists of  Subsequent digitisation projects are trying to rectify this. 



Currently researchers access this either through Gale, or through the British Library as an external researcher. Many researchers have requested access to the collection through Gale, which they will apparently do in exchange for a fee for the costs of the hard drives and presumably some labour time. The specifics of the XML used, and some code for extracting the data, are available in the following chapter.

Some researchers have also got access to the collection through 

## GALE

## HMD data- on repository

## Luxembourg data


