--- 
title: "Demystifying Newspaper Data with R (and a tiny bit of Python)"
author: "Yann Ryan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [r_for_news.bib]
csl: mhra.csl
github-repo: yannryanBL/r-for-news-data
description: "This is a book to help new and existing users find, process and analyse historical newspaper data, using the programming language R, and its IDE R-Studio"
---

# Preface & Acknowledgements

I spent the last year or so working at the British Library as a Curator of Newspaper Data. It was an experimental position, conceived on the premise that the _data_ generated by newspaper digitisation projects, in this case the _Heritage Made Digital_ project, deserves its own curatorial role and set of practices.

It was an exciting time to work on such a project while 'big data' analysis using newspaper content, by historians, is no longer in its infancy, it is firmly in a soul-searching adolescence, and it's been exciting working on an evolving discipline, one which is developing its own set of practices, understanding where and how its bias works and the implications this might have, and generally moving from a sense of naive optimism to a practice which is more academically and mathematically rigorous and self-reflective. 

The British Library was a wonderful, inspiring place to work, and over the year I spent a lot of time getting to grips with the extent and wonderful complications involved in getting access to and analysing the data that the Library has (and elsewhere). This book, then, is meant as something of a roadmap - we are not quite at the final stage of the journey but great steps forward have been taken. The only way I know how to get there is through a programming language, and specific examples.

This book is based on my experiences in this position, as well as some from my own PhD work. It's conceived as somewhere between a 'how-to' and an inspirational (or aspirational) piece of writing intending to survey and encourage the use of newspaper data. It does not cover everything, partially because of my own shortcomings and partially because newspaper data is a vast, incomprehensible and ever-expanding field. I am grateful to those who have taken the time to clear the dense thickets (or perhaps sweeping for mines is a more suitable metaphor, given the risks of failure), including Ryan Cordell, Jo Guldi, Bob Nicholson and Paul Fyfe.

I owe a huge debt of gratitude to the Library, and in particular the Lead Curator of News and Moving Image, Luke McKernan, for his help and support during my time, as well as the rest of the News Collections Team, Beth and Stephen, the Digital Scholarship team, and the wonderful team working on the _Living with Machines_ project. 

This is a book about how to find, download and use this newspaper data. It has been written, in part, by an employee who worked at the British Library, but it does not represent the Library's views in anyway. This is a record of my experience rather than any official information or advice - policies may change, and although I hope to update the book when that happens, I can't guarantee that the information here will be up to date. 